
CREATE TABLE CITY(
	CITY_ID INT NOT NULL,
	[NAME] VARCHAR(40) NOT NULL,
	[LOCATION] SMALLINT,
	PRIMARY KEY(CITY_ID),
	FOREIGN KEY([LOCATION]) REFERENCES LOCATION(LOCATION_ID)
	ON UPDATE CASCADE
	ON DELETE SET NULL)

INSERT INTO CITY VALUES 
	(1, 'NEW YORK', 122)

INSERT INTO CITY VALUES 
	(2, 'CHICAGO', 123)

INSERT INTO CITY VALUES 
	(3, 'DOLGOPRUDNY', 123)

INSERT INTO CITY VALUES 
	(4, 'DALLAS', 124)

INSERT INTO CITY VALUES 
	(5, 'BOSTON', 167)
	


SELECT * FROM LOCATION